---
- name: Instalar bind9
  apt: 
    name: "{{ item }}"
    state: latest
  loop: "{{ bind9_packages }}"
  notify: restart_bind9

- name : hostname fact
  set_fact:
    ansible_fqdn: dns.{{ domain }}

#- name: copiar named.conf file
#  template:
#    src: named.conf.j2
#    dest: /etc/bind/named.conf
#    owner: root
#    group: bind
#    mode: 0660
#  notify: restart_bind9

- name: copiar named.conf.local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0640
  notify: restart_bind9

- name: crear directorio de zonas
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy forward file
  template:
    src: db.{{ domain }}.j2
    dest: "/etc/bind/zones/db.{{ domain }}"
    owner: root
    group: bind
    mode: 0640
  loop: "{{ records.items() | list }}"
  notify: restart_bind9

- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: "/etc/bind/zones/db.{{ rev_domain }}"
    owner: root
    group: bind
    mode: 0640
  loop: "{{ records.items() | list }}"
  notify: restart_bind9
...